language: python
python:
  - "3.6"
install:
  - pip install -q pytest
  - pip install -q --pre torch==1.6.0.dev20200528 -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
  - pip install -q -r requirements.txt
  - python setup.py develop
script:
  - pytest tests
  - ./tests/test_shakespeare.sh
